Add registration page
Omams21/PropertyPro pull request #2
Opened 2022-02-08 11:53 UTC by Omams21

2022-02-10 12:36 UTC, mykelmatics reviewed
It really looks good, I just dropped  few comments

2022-02-11 09:06 UTC, Shukura2 requested changes
Weldone.

2022-02-11 09:06 UTC, Shukura2 commented on Desktop/property-pro-app/src/pages/Signin/Signin/Signin.js
> +      <div className=" firstcontainer">
Same here, try to look through the code and make similar changes where needed.

2022-02-11 09:06 UTC, Shukura2 commented on Desktop/property-pro-app/src/pages/Signin/Signin/Signin.js
> +          {" "}
Let's take this out, since its not part of the code.

2022-02-15 09:33 UTC, merged