worked on property pages
Omams21/PropertyPro pull request #3
Opened 2022-02-10 12:20 UTC by Omams21

2022-02-15 13:55 UTC, Pauliski commented on Desktop/property-pro-app/src/pages/Buy/Buy.js
> +      <div className="property_wrapper">
I think you should change this from snake-case

2022-02-15 13:59 UTC, Pauliski commented on Desktop/property-pro-app/src/pages/Rent/Rent.js
> +      {propertyData.map((property) =>
I think this map item is supposed to have a unique key, try to  work with the browser console for error

2022-02-15 14:01 UTC, Pauliski commented on Desktop/property-pro-app/src/pages/Rent/Rentproperty.js
> +              <span className="bold">{bedNo}</span>Bed
you might want to look at giving your HTML element a descriptive className

2022-02-15 14:02 UTC, Pauliski requested changes
Nice work! just need some little touches

2022-02-16 06:53 UTC, Shukura2 approved these changes
Cool

2022-07-01 10:36 UTC, merged